### ISSUE TITLE
Unable to set OPENAI Key

### ISSUE THREAD

**Issue by munyanyika24** [VRSEN/agency-swarm#103]
I am trying to get the agency swam project running locally on my machine but I keep getting an issues setting the Open AI API key.
I used agency genesis to generate the agency

![Screenshot 2024-04-05 at 12 38 47](https://github.com/VRSEN/agency-swarm/assets/3600891/b1c50159-eddc-4b5c-9f40-9cf328c41b83)

**Comment by VRSEN** [comment]
Please create a `.env` file with your `OPENAI_API_KEY` variable inside and drop it in the same directory from where you are running your agency. Also I recommend updating to latest version
