### ISSUE TITLE
I just can figure this one out: FAIL: test_relevance_openapi_schema (test_tool_factory.ToolFactoryTest.test_relevance_openapi_schema)

### ISSUE THREAD

**Issue by 360elements360** [VRSEN/agency-swarm#105]
FAIL: test_relevance_openapi_schema (test_tool_factory.ToolFactoryTest.test_relevance_openapi_schema)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User\Documents\CODE PROJECTS\agency-swarm\tests\test_tool_factory.py", line 106, in test_relevance_openapi_schema
    result_data = output['output']['transformed']['data']
                  ~~~~~~^^^^^^^^^^
KeyError: 'output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Documents\CODE PROJECTS\agency-swarm\tests\test_tool_factory.py", line 112, in test_relevance_openapi_schema
    raise AssertionError("Expected key not found in the output.")
AssertionError: Expected key not found in the output.

----------------------------------------------------------------------
Ran 14 tests in 75.816s

FAILED (failures=1)

**Comment by VRSEN** [comment]
Avoid testing the tool factory as it requires API keys for various endpoints. For now, you can only run the `test_agency` file. Once you submit a pull request, I can execute the entire test workflow.
