### ISSUE TITLE
Problem with Azure OpenAI

### ISSUE THREAD

**Issue by Chmurexxx** [VRSEN/agency-swarm#109]
Executing code:
from agency_swarm import Agency

agency = Agency([ceo, [ceo, agent1]])

I got this error:

`---------------------------------------------------------------------------
BadRequestError                           Traceback (most recent call last)
[<ipython-input-9-8c249ad2af08>](https://localhost:8080/#) in <cell line: 3>()
      1 from agency_swarm import Agency
      2 
----> 3 agency = Agency([ceo, [ceo, agent1]])

6 frames
[/usr/local/lib/python3.10/dist-packages/openai/_base_client.py](https://localhost:8080/#) in _request(self, cast_to, options, remaining_retries, stream, stream_cls)
    986 
    987             log.debug("Re-raising status error")
--> 988             raise self._make_status_error_from_response(err.response) from None
    989 
    990         return self._process_response(

BadRequestError: Error code: 400 - {'error': {'type': 'invalid_request_error', 'param': 'model', 'code': 'model_not_found'}}`

There should be some specific model deployments on my Azure OpenAI service? 
Thanks for help

**Comment by VRSEN** [comment]
Yes, you need to first create a deployment on Azure OpenAI Studio for a specific model, and then enter deployment name when intializing your agents for `model` parameter.
