### ISSUE TITLE
Temperature Integration on Agent Creation

### ISSUE THREAD

**Issue by hicknughes** [VRSEN/agency-swarm#111]
Hi there! Temperature can be set with the creation of an agent within OpenAI. It would be great to add that to the Agent class as an input parameter so that individual Agent temperatures can be controlled within the Agency.  

Thanks in advance!

**Comment by VRSEN** [comment]
Hey yeah, there were a lot of updates so I am working on it right now. It's almost done. You can checkout `dev/assistants-v2` branch

**Comment by hicknughes** [comment]
Great! Will that version also allow for the use of a specific agent on a specific thread? I have been using OpenAI's Assistants API to deploy agents on specific threads in an effort to control token cost creep. Is there a better solution that exists or in development within the agency-swarm framework?

**Comment by VRSEN** [comment]
There are new parameters in agency and agent classes to control token costs from Assistants V2 now. The default for `max_prompt_tokens` is 25000 atm.
