### ISSUE TITLE
Connecting agency-swarm to own gpt-like LLM API like the new Llama-3-70B-Instruct

### ISSUE THREAD

**Issue by NVS-AI** [VRSEN/agency-swarm#112]
So, as the title says. I've been wondering how difficult would it be to replace the openai API with connector to a Llama instance running somewhere, potentially even locally (I do have the compute power). Seems at first glance the API integration is quite hot-swappable, but I wanted to get the creator's thoughts on the matter. Having an option like this could mean significant performance upgrade and cost savings.

**Comment by samuelmukoti** [comment]
I’ve heard the creator speak many times on his YouTube about why he only will support OpenAI right now. He believes in building upon the best framework and tools available and OpenAI is the leader right now, he also mentioned how he leverages the OpenAI assistance API which is specific and I’m not sure if supported by other LLMs weather local or cloud.

Sam

**Comment by codermrrob** [comment]
I heard in another recent YouTube video today that @VRSEN is looking into this. It would be very cool, OpenAI is restrictively expensive for solo developer to experiment with :( and while I have been making great progress I could easily run up bills of 100+ a week building out and refining an agency. Having a cheaper option for learning and experimenting with I think is going to be important for this framework to gain traction, as good as it is.

**Comment by KMouratidis** [comment]
If you have an OpenAI-compatible server (e.g. vllm / srt) you can point your requests to that either by patching the OpenAI library directly, or by messing with your routing/DNS configs, or it may even be as simple as using a different `OPENAI_BASE_URL` environment variable.

For example you can start a vllm server on a linux terminal:

```
~$ sudo docker run --rm --runtime nvidia --gpus all -p 8000:8000 --ipc=host vllm/vllm-openai:latest --model TheBloke/TinyLlama-1.1B-Chat-v1.0-GPTQ --dtype float16
```

and on another terminal run the program you want:

```
~$ OPENAI_BASE_URL=http://127.0.0.1:8000/v1 python

import openai
client = openai.OpenAI(api_key="whatever")
chat_completion = client.chat.completions.create(
    messages=[{"role": "user", "content": "Say this is a test"}],
    model="TheBloke/TinyLlama-1.1B-Chat-v1.0-GPTQ",
)
```

```
```

But for agency-swarm you need `/v1/assistants` implemented. So maybe a backend like https://github.com/MLT-OSS/open-assistant-api could work?

**Comment by VRSEN** [comment]
Hey everyone, I'm currently testing the repo https://github.com/datastax/astra-assistants-api, which worked with Assistants v1. However, it may need some time to update to v2. Nonetheless, for any project that mimics the Assistants API, you just need to replace the OpenAI client like this:

```python
import openai
from agency_swarm import set_openai_client
client = openai.OpenAI(api_key="whatever", base_url="http://127.0.0.1:8000/")
set_openai_client(client)
```

That should literally be it, if it's fully compatible. 

If you manage to get any of these repos working, please ping me, and I'll give you a shoutout on the next video.

**Comment by NVS-AI** [comment]
> If you manage to get any of these repos working, please ping me, and I'll give you a shoutout on the next video.

Thanks, will do :) Currently playing around with starting a Llama 3 instance locally. then gonna see about a wrapper API... Worst case scenario, will make one that mimics the openai API.

**Comment by jay377** [comment]
> Author

Yes please somebody make this work, i actually want to learn a real agents tool that's production capable but to poor to experiment on openai

**Comment by slavakurilyak** [comment]
@VRSEN [astra-assistants-api](https://github.com/datastax/astra-assistants-api) currently has 82% [coverage](https://github.com/datastax/astra-assistants-api/blob/main/coverage.md) for OpenAI

In the meanwhile, check out [MLT-OSS/open-assistant-api](https://github.com/MLT-OSS/open-assistant-api) and https://github.com/BerriAI/litellm/issues/2842 (planned feature)

**Comment by Ga68** [comment]
> Thanks, will do :) Currently playing around with starting a Llama 3 instance locally. then gonna see about a wrapper API... Worst case scenario, will make one that mimics the openai API.

@NVS-AI ¿any luck? I was excited to see something taking a stab at this.

**Comment by briancg42** [comment]
Thank you @VRSEN, this is a huge step ⚡


> Got this to work flawlessly with any llms https://github.com/VRSEN/open-assistant-api You can even use different llms for different agents
> 
> Video coming up shortly...

**Comment by codermrrob** [comment]
Great work - It's exactly what this space needs. Can't wait to try it out.

**Comment by phact** [comment]
@codermrrob separate LLM for tool selection is something we've been thinking about a bunch. 
I went ahead and created https://github.com/datastax/astra-assistants-api/issues/28

We'll prioritize it after we have support for assistants v2.

**Comment by slavakurilyak** [comment]
@VRSEN Excellent work on `open-assistant-api`

By the way, `litellm` also added [support for openai assistants](https://github.com/BerriAI/litellm/pull/3455)

**Comment by VRSEN** [comment]
Hey @slavakurilyak, yes, I saw that, however we need it to be supported in their proxy server for seamless integration. Once that's done I will update the docs here: https://vrsen.github.io/agency-swarm/advanced-usage/open-source-models/
