### ISSUE TITLE
suggestions: typed code, design by contract

### ISSUE THREAD

**Issue by Morriz** [VRSEN/agency-swarm#114]
Hi, I think this code base is not following best practices and could use the following:

- typing: I'd say research the benefits if you care
- design by contract: same, I suggest to investigate. It offers clear separation of concerns, and does away with useless input checking

**Comment by VRSEN** [comment]
Please specify the lines of code or files where types are missing, and explain where DbC should be implemented and why. 

If you continue to open issues like this, I will have to block you.
