### ISSUE TITLE
missing Union command in agent.py

### ISSUE THREAD

**Issue by neural-oracle** [VRSEN/agency-swarm#116]
Hi ... I installed agency-swarm today in a new conda environment.
Even thought the installation finished successfully I had a TypeError when starting with agency-swarm genesis ...

I solved the issue by changing line 63 typing
`response_format: Union[str,dict] = "auto",`

Instead of 
`response_format: str | dict = "auto",`

After the change everything worked.

**Comment by Ga68** [comment]
That could be a Python version thing. I'm not certain but I think that Python, at some point, changed the syntax for "or typing".
