### ISSUE TITLE
Consistent FileWriter Errors

### ISSUE THREAD

**Issue by spocksbrain** [VRSEN/agency-swarm#120]
Anytime Devid goes to save something  and sometimes the Browsing Agent similar errors.  Also loses its place in the directory structure, moving down a level then not being able to validate the directory and write the file. 

Error: llm_validator() got an unexpected keyword argument 'openai_client'. Trying again.
THREAD:[ PlannerAgent -> BrowsingAgent ]: URL https://platform.openai.com/playground?assistant=asst_RAEE49tiwJG68jVvsulfEZUf&mode=assistant&thread=thread_Y04QrqGPxcdIe21SnFhFI4zt
THREAD:[ PlannerAgent -> Devid ]: URL https://platform.openai.com/playground?assistant=asst_D5HxnyVhXW3Uwx2D8JRygVpi&mode=assistant&thread=thread_zAgVmq6UHWZrJdzegm65UnzP
Error: llm_validator() got an unexpected keyword argument 'openai_client'. Trying again.
Error: llm_validator() got an unexpected keyword argument 'openai_client'. Trying again.
Error: llm_validator() got an unexpected keyword argument 'openai_client'. Trying again.
Error: llm_validator() got an unexpected keyword argument 'openai_client'. Trying again.
Error: llm_validator() got an unexpected keyword argument 'openai_client'. Trying again.
Error: llm_validator() got an unexpected keyword argument 'openai_client'. Trying again.
Error: llm_validator() got an unexpected keyword argument 'openai_client'. Trying again.
Error: llm_validator() got an unexpected keyword argument 'openai_client'. Trying again.
Error: llm_validator() got an unexpected keyword argument 'openai_client'. Trying again.
^CKeyboard interruption in main thread... closing server.
seluser@8a763a2da35f:/app/CodeSolutionAgency$

**Comment by VRSEN** [comment]
In the latest agency swarm update, there were some breaking changes with the instructor. I have updated the agency swarm lab repository to accommodate these changes. Please pull the latest version and try again.
