### ISSUE TITLE
No way to point Agency-Swarm.exe to other APIs

### ISSUE THREAD

**Issue by Mr4ntiVirus** [VRSEN/agency-swarm#122]
Id like to point agency-swarm.exe to other APIs such as Azure OpenAI however it does not appear that this is possible.

**Comment by VRSEN** [comment]
It is possible, please check docs here: https://vrsen.github.io/agency-swarm/advanced-usage/azure-openai/

**Comment by Mr4ntiVirus** [comment]
Thank you for your response!

I apologize if I still need a bit of guidance. I really like the framework.
Could you be more specific about where to update the pointer to the API?

I don’t have confidence at the moment that I updated the right script. It
may be that someone more familiar experienced had little trouble but
unfortunately I need a little more detail in the Azure instructions to know
exactly which scripts to edit.

If Agency Swarm is expanding into open source models with Assistance API
support, perhaps an enhancement request would be helpful and have the
framework include a clear place to establish the API used with an agency.

I would suggest breaking out a separate config file just for the definition
of the API, and perhaps a few other key setup variables that are popular to
edit. End users are very familiar with editing config files, and I would
rather leave the core scripts in your framework as is. They’re great. Keep
the good work!
