### ISSUE TITLE
Unable to use Azure OpenAI

### ISSUE THREAD

**Issue by scchengaiah** [VRSEN/agency-swarm#123]
Hello,

I am getting the following error while following this [Azure Notebook](https://github.com/VRSEN/agency-swarm/blob/main/notebooks/azure.ipynb) example.

```text
openai.BadRequestError: Error code: 400 - {'error': {'message': "Unknown parameter: 'tool_resources'.", 'type': 'invalid_request_error', 'param': 'tool_resources', 'code': 'unknown_parameter'}}
```

Do we need to enable some additional configuration to make it functional ?

Also, I would like to use Azure OpenAI endpoint with `Genesis` agency as demonstrated in this [notebook](https://github.com/VRSEN/agency-swarm/blob/main/notebooks/genesis_agency.ipynb). However, I could not find a way to inject the `azure deployment` as `model` to the Agency. Would appreciate if someone can share a way to achieve this ?

**Comment by VRSEN** [comment]
Seems like azure still hasn't updated to assistants v2. Try with previous version

`pip install agency-swarm==0.1.7`
