### ISSUE TITLE
How to connect chat with AI agency in Telegram and WhatsApp?

### ISSUE THREAD

**Issue by innodev-group** [VRSEN/agency-swarm#124]
How can I use Telegram bot or Watsapp chat instead of Gradio chat so that only @User message is shown?

**Comment by VRSEN** [comment]
You would first deploy your agents as an API and then integrate this endpoint with Telegram or WhatsApp webhooks. We will add this to our SaaS and release some templates in our course later, however, it will never be added directly into the framework. 

In the meantime, I recommend finding some tutorials on how to create telegram/whatsapp bots and taking it from there.
