### ISSUE TITLE
Sometimes Function(sendMessage to one other agent)  may do twice。

### ISSUE THREAD

**Issue by dukuang596** [VRSEN/agency-swarm#131]
![image](https://github.com/VRSEN/agency-swarm/assets/6032115/7c2c88f6-9ba3-4b46-a090-6690b5426524)
![image](https://github.com/VRSEN/agency-swarm/assets/6032115/32d987c7-74d3-44cc-a2a0-9b701bca051a)

**Comment by VRSEN** [comment]
Agent can get a response from another agent and then ask a follow up question. That's normal.
