### ISSUE TITLE
feat:Add support zip, tar.gz and git repo uploading as files

### ISSUE THREAD

**Issue by sjurajpuchky** [VRSEN/agency-swarm#143]
Add support zip, tar.gz and git repo uploaded as files.

**Comment by VRSEN** [comment]
Where are you trying to upload zip? In Gradio interface or using `files_folder`? 

It should work with `files_folder` and upload your zip to use with code interpreter

**Comment by sjurajpuchky** [comment]
Let me fix this to be :100:

**Comment by sjurajpuchky** [comment]
Fix done
