### ISSUE TITLE
Is there a way to have debugging/verbose output

### ISSUE THREAD

**Issue by tlnet1981** [VRSEN/agency-swarm#147]
Hi all,

I started playing around with the framework, and the lab. Is there a way to get logging/verbose output what exactly its doing on the command line?

Specially, when it tests code, i cannot see what it is doing, it gets stuck and waits for someone to close the tool its testing at the moment. But i only can close the whole server.

Best regards & many Thanks!

**Comment by VRSEN** [comment]
Hey, if you need to add detailed debugging in your tool logic, the only way is to do it manually with print/logger statements
