### ISSUE TITLE
Need "ChatDev" type workflow example

### ISSUE THREAD

**Issue by haltingstate** [VRSEN/agency-swarm#149]
Please make an example, of a "ChatDev" type workflow, for generating software, running it, testing it, from a text prompt description or a .md specification file as input.

It would help people a lot. As many people are coming here from ChatDev.

**Comment by VRSEN** [comment]
I'll consider adding this in [agency-swarm-lab](https://github.com/VRSEN/agency-swarm-lab). In the meantime checkout https://youtu.be/BEpDRj9H3zE?si=YApi1qQAjPXI0Eei
