### ISSUE TITLE
Transferring to Async

### ISSUE THREAD

**Issue by gregnwosu** [VRSEN/agency-swarm#15]
May I suggest initially making duplicate files AsyncAgent, AsyncBasetool etc and renaming the functions to be async

We dont yet actually have to make them asynchronously efficient, but just use the async mechanism around synchronised code

Later we can go into the methods and make them more efficient, once the interface is defined and proved to be working, 

what do others think on this approach?

**Comment by gregnwosu** [comment]
Ive been looking at this and it seems that it affects everything, if you have an async thread you will need to have an async agent to run it from, it kinda just spreads backwards to wherever the thread is being called from. Happy to start work on this  but dont you think that you cant have an async thread without having an async agent?

**Comment by VRSEN** [comment]
This is done now. I will release a video on how to use this week.
