### ISSUE TITLE
Token Usage Statistics

### ISSUE THREAD

**Issue by bhakimiy** [VRSEN/agency-swarm#158]
Hello,

Is there any way to see the token usage statistics?

**Comment by ivanguerron21** [comment]
Hi, have you come to a solution?

**Comment by VRSEN** [comment]
Hi, I will add this next week in 0.2.7 release

**Comment by ivanguerron21** [comment]
Thanks!! Are you going to separate input and output tokenization?

**Comment by ivanguerron21** [comment]
Hi @VRSEN, when are we going to be able to see these upgrade
