### ISSUE TITLE
Genesis with Open Source / Third Party models

### ISSUE THREAD

**Issue by phact** [VRSEN/agency-swarm#160]
A few folks on discord have asked about the possibility of running `genesis` with open source or third party models. 

@VRSEN would you be okay if I implement this? 

I was thinking to add a `model` flag to the CLI and wrap / set the model only if the flag is set.

**Comment by qwaszaq** [comment]
ollama possible?

**Comment by SwapnaliDhotre12** [comment]
Can't find discord server for agency swarm. @phact can you please share/invite? Thank you!

**Comment by phact** [comment]
Agency swarm discord is https://discord.com/invite/cw2xBaWfFM
[astra-assistants](https://github.com/datastax/astra-assistants-api) discord is https://discord.com/invite/MEFVXUvsuy

**Comment by phact** [comment]
Yes @qwaszaq that would include ollama. I'll try to find time for this in the next week or so.

**Comment by phact** [comment]
Taking a stab at this today
