### ISSUE TITLE
File handling, thread_id and assistant_id using backend version of Agency Swarm

### ISSUE THREAD

**Issue by Ruhul-Quddus-Tamim** [VRSEN/agency-swarm#174]
If I use the backend version of the agency -

`completion_output = agency.get_completion("Please create a new website for our client.")`

I'm aware that `agency.get_completition()` has `attachment` parameter but is there any other way round like how `custom_demo()` function do the file handling management? The same way `agency.get_completion()` function can do the file handling too? If not so, then do I've to create my own function for uploading the file to OpenAI server first, get the `file_id` and then pass this parameter as attachment?

Another thing regarding the `thread_id` and `assistant_id` - Right now in our GenAI application, we are storing all the chat history into the database, if we want to continue the same chat then how can I pass the `thread_id` and `assistant_id`? I'm aware that the existing `settings_path: str = "./settings.json"` file can be used for the continuation of the same chat but I need to retrieve the existing `thread_id` and `assistant_id` to maintain the chat history in my application.

Thanks!

**Comment by bonk1t** [comment]
Hi @Ruhul-Quddus-Tamim! 

Here’s an example solution for file uploading using the Gradio UI that might help:
https://github.com/VRSEN/agency-swarm/issues/161

It looks like you have a few different questions, and I wanted to let you know that Discord (#issues-and-discussion section) is a great place for us to assist you more quickly with these.
Feel free to reach out there, and we’d be happy to help further!

**Comment by bonk1t** [comment]
@Ruhul-Quddus-Tamim 

To manage `thread_id` in your app:

1. **Store Thread IDs**: When creating a new chat, save the `thread_id` in your database.
2. **Retrieve Thread IDs**: When continuing a chat, load the stored `thread_id` from the database.
3. **Use in Agency Swarm**: Modify Agency Swarm to accept and use these thread IDs with callbacks for loading/saving state.

This allows you to:
- Start new threads for new chats.
- Continue existing conversations with stored `thread_ids`.
- Return and store updated `thread_ids` with responses.

## Example of Callbacks in Agency

```python
agency = Agency(
    agents=[ceo],
    threads_callbacks={
        'load': lambda: load_threads(chat_id),
        'save': save_threads,
    }
)
```
