### ISSUE TITLE
Optimize Communication Between Entry Point Agent and Other Agents Using sendMessage

### ISSUE THREAD

**Issue by wass-21** [VRSEN/agency-swarm#175]
We are facing an issue where the entry point agent occasionally sends incorrect or malformed information when communicating with other agents. To address this, I want to enforce that all messages sent by the entry point agent are in JSON format to improve message consistency and avoid errors in communication. Specifically, I need guidance on:

How can I ensure that all messages sent by the entry point agent are in JSON format?
Is there a way to optimize the sendMessage function to enforce JSON format for all outgoing messages?

**Comment by VRSEN** [comment]
Hey did you try to enable JSON mode for the CEO agent? Also, discord is the best place for questions like this so we can assist you quicker
