### ISSUE TITLE
Azure OpenAI not working with Agents - Unknown parameter: 'tools[0].function.strict

### ISSUE THREAD

**Issue by simoninnyc** [VRSEN/agency-swarm#177]
Not sure if this is an Azure OpenAI issue or a simple configuration fix for agency-swarm. Here's my code:

client = AzureOpenAI(
    api_key=settings.OPENAI_KEY,
    api_version=settings.OPENAI_VERSION,
    azure_endpoint=settings.OPENAI_ENDPOINT,
    timeout=5,
    max_retries=5,
)

set_openai_client(client)

ceo = Agent(
    name="CEO",
    description="Responsible for client communication, task planning and management.",
    instructions="You must converse with other agents to ensure complete task execution.",  # can be a file like ./instructions.md
    files_folder="./files",  # files to be uploaded to OpenAI
    schemas_folder="./schemas",  # OpenAPI schemas to be converted into tools
    temperature=0.5,  # temperature for the agent
    max_prompt_tokens=25000,  # max tokens in conversation history
    model=settings.OPENAI_MODEL_GPT_4o
)

dev = Dev(id=model=settings.OPENAI_MODEL_GPT_4o)

agency = Agency(
    [ceo,
     [ceo, dev]
    ]
)

agency.run_demo()

Error code: 400 - {'error': {'message': "Unknown parameter: 'tools[0].function.strict'.", 'type': 'invalid_request_error', 'param': 'tools[0].function.strict', 'code': 'unknown_parameter'}}

**Comment by vishnureddysai** [comment]
Yah even I’m facing same issue can anyone help to resolve it

**Comment by bonk1t** [comment]
@simoninnyc @vishnureddysai 
Please provide more details:
- Library versions: agency-swarm, openai
- Model that you use. 

Currently, Structured Outputs is only supported on the gpt-4o model, specifically version 2024-08-06[4](https://learn.microsoft.com/ja-jp/azure/ai-services/openai/how-to/structured-outputs). This is a crucial requirement, as older models or different versions do not have this capability.

**Comment by vishnureddysai** [comment]
Agency swarm version : 0.3.0
Open ai - 1.41.0 & even tried with latest version 
Model version : gpt-4o - 2024-05-13 version

**Comment by vishnureddysai** [comment]
When I use 2024-08-06 version I’m getting this below error 

this deployment is not compatible with assistant functionality 
![IMG_4558](https://github.com/user-attachments/assets/847cdc55-3f87-404d-8553-603bcd37a9ce)

**Comment by bonk1t** [comment]
> gpt-4o - 2024-05-13 version
Either update the model, or do not use `strict: true` in your tool schemas. 
In your case @vishnureddysai, you might need to check your API version. And contact OpenAI support it case of issues.

**Comment by vishnureddysai** [comment]
I have tried both the ways still facing same issue but it’s the issue related to using tools

**Comment by bonk1t** [comment]
In order to install from the main branch: 
`pip install git+https://github.com/VRSEN/agency-swarm.git`

**Comment by vishnureddysai** [comment]
I tried and tested that still getting same error

**Comment by aizech** [comment]
API Version:
Which API Version on Azure do you use in your settings?
AZURE_API_VERSION = "2024-05-01-preview"   # this is the actual version
https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/assistant 

Model Deployment
Check, if the model gpt-4o is deployed in your Azure resource and region?
https://oai.azure.com/resource/deployments

**Comment by vishnureddysai** [comment]
I have used both 2024-05-01-preview & latest model version in the both cases I was facing the same issue 

and also everything works if I don’t use any tools 
Issue occurres while using the tools

**Comment by aizech** [comment]
I just saw that there is a newer API version, where strucutred outputs are supported:

2024-08-01-preview

https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/structured-outputs?tabs=python-secure

**Comment by simoninnyc** [comment]
> Hey guys, a push for this is already in main, I will make a release shortly. Install from main and test again please if you can

Thanks! This fixed the issue for me. Discovered a bug related to the Browsing Agent with Azure OpenAI but I'll create another ticket.
