### ISSUE TITLE
Azure integration error when try to make an Agency: BadRequestError: Unsupported data type

### ISSUE THREAD

**Issue by arcossci** [VRSEN/agency-swarm#182]
I got an error when I try to run with gpt4o (Azure) with the last version !pip install -U agency-swarm==0.3.1
The conection with llm is tested and worked well but the problem is when I tried to make the Agency, please help me

## Mi code:
------------------------------
from openai import AzureOpenAI
from agency_swarm import set_openai_client
import os

os.environ["AZURE_OPENAI_KEY"] = "..."
os.environ["AZURE_ENDPOINT"] = "https://wafer-m1tixc2n-eastus2.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2024-08-01-preview" 

client = AzureOpenAI(
    api_key=os.getenv("AZURE_OPENAI_KEY"),
    api_version="2024-08-01-preview",
    azure_endpoint=os.getenv("AZURE_ENDPOINT"),
    timeout=5,
    max_retries=5,
)
set_openai_client(client)
from agency_swarm import Agent
ceo = Agent(name="ceo")
from agency_swarm import Agency
agency = Agency([ceo])
agency.run_demo()

----------------------------
## the error

BadRequestError                           Traceback (most recent call last)
[<ipython-input-4-45e61d03a8f6>](https://localhost:8080/#) in <cell line: 5>()
      3 ceo = Agent(name="ceo")
      4 from agency_swarm import Agency
----> 5 agency = Agency([ceo])
      6 agency.run_demo()

6 frames
[/usr/local/lib/python3.10/dist-packages/openai/_base_client.py](https://localhost:8080/#) in _request(self, cast_to, options, retries_taken, stream, stream_cls)
   1056 
   1057             log.debug("Re-raising status error")
-> 1058             raise self._make_status_error_from_response(err.response) from None
   1059 
   1060         return self._process_response(

BadRequestError: Unsupported data type

**Comment by kauttoj** [comment]
For Azure, the endpoint url must only contain the base, i.e., in this case
azure_endpoint="https://wafer-m1tixc2n-eastus2.openai.azure.com"
The actual model is defined when creating the agent. You can see all created agents in your Azure platform.
