### ISSUE TITLE
TypeError: Client.__init__() got unexpected keyword argument 'proxies' with OpenAI SDK 1.54.4

### ISSUE THREAD

**Issue by golpeandopelotas** [VRSEN/agency-swarm#192]
### Description
When using agency-swarm 0.4.0 with OpenAI SDK 1.54.4, getting error during client initialization:
`TypeError: Client.__init__() got an unexpected keyword argument 'proxies'`

### Environment
- agency-swarm version: 0.4.0
- OpenAI SDK version: 1.54.4
- Python version: 3.10
- OS: macOS

### Steps to Reproduce
1. Install agency-swarm 0.4.0
2. Install OpenAI SDK 1.54.4
3. Try to initialize an agent

### Error Message
```python
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'
```

### Expected Behavior
The client should initialize correctly with the current OpenAI SDK version.

### Additional Context
The error seems to be related to how the OpenAI client is initialized in the package's `oai.py`. The current version of OpenAI SDK doesn't accept the `proxies` parameter in client initialization.

### Possible Solution
Consider updating the client initialization to match the current OpenAI SDK requirements, removing unsupported parameters like `proxies`.

**Comment by bonk1t** [comment]
Hey @golpeandopelotas, thank you for reporting this! Please try the new version 0.4.1, it should fix the issue.
