### ISSUE TITLE
Feature Request: Prevent Agents from Being Used as Tools

### ISSUE THREAD

**Issue by AMGMNPLK** [VRSEN/agency-swarm#208]
**Description**
When building complex multi-agent systems, it's common to accidentally use agents as tools, leading to errors like `AttributeError: 'NoneType' object has no attribute 'ToolConfig'`. This happens because agents have a similar interface to tools (e.g., `run` method) but should be communicated with via message passing.

**Current Behavior**
```python
# This is possible but causes errors:
result = await agent.SomeOtherAgent(action="do_something").run()

# This is the correct way:
result = await agent.send_message(
    recipient="SomeOtherAgent",
    message="do_something"
)
```

**Proposed Solution**
Add built-in validation to enforce proper agent communication patterns:

1. Extend the Agent class with validation:
```python
class Agent:
    @staticmethod
    def response_validator(message: str = None, response: str = None) -> str:
        """Validate agent responses to ensure proper communication."""
        if not response:
            return ""
            
        # Check for tool-like usage of agents
        agent_names = ["AgentA", "AgentB"]  # Could be auto-populated
        for agent in agent_names:
            if f"{agent}Tool" in response:
                return f"Error: Use send_message for {agent} communication"
        
        return response
```

2. Add a registry system for agents:
```python
class Agency:
    def __init__(self):
        self._agent_registry = {}
    
    def register_agent(self, agent_name: str, agent_class: Type[Agent]):
        self._agent_registry[agent_name] = agent_class
        
    def validate_communication(self, sender: str, recipient: str, message: str):
        if recipient not in self._agent_registry:
            raise ValueError(f"Unknown agent: {recipient}")
```

3. Add documentation and examples:
```python
# Example usage
agency = Agency()
agency.register_agent("AgentA", AgentAClass)
agency.register_agent("AgentB", AgentBClass)

# This would raise a validation error
result = await agent_a.AgentB(action="do_something").run()

# This would work
result = await agent_a.send_message(
    recipient="AgentB",
    message="do_something"
)
```

**Benefits**
1. Prevents common errors in agent implementation
2. Forces proper message-passing patterns
3. Makes debugging easier with clear error messages
4. Enables static analysis of agent communication

**Questions**
1. Should validation be opt-in or opt-out?
2. How should the agent registry be populated?
3. Should there be different validation levels (strict/lenient)?

**Comment by bonk1t** [comment]
Hey @AMGMNPLK Is your issue related to the Agency Swarm framework? Please submit issues written by you, rather than AI-generated content with potential hallucinations. Kindly describe any problems you’re encountering. Use https://github.com/VRSEN/agency-swarm/discussions for discussions.

**Comment by bonk1t** [comment]
@AMGMNPLK 
I see that your actual error is: AttributeError: 'NoneType' object has no attribute 'ToolConfig'.

Could you please update your request so it only includes the real issue description (rather than AI-generated suggestions)? To assist you effectively, we need to see your custom tool code and how you’ve set up your agency.
