### ISSUE TITLE
Agents ability to read file using retrieval tool and file upload with Assistants API

### ISSUE THREAD

**Issue by TerminalGravity** [VRSEN/agency-swarm#21]
I've tried to run a swarm with a DeveloperAgent to access a JSON file. I initialized the swarm and ran the gradio demo from a colab notebook. Before i started the Gradio demo with the agency I uploaded the files to the DeveloperAgent on the OpenAI assistants API playground as well as turning on retrieval. I realize that's not exactly how 'agency-swarm' is designed to operate however, how can the Assistants API be utilized fully in a swarm? 

Has anyone got their agents to read files?

**Comment by VRSEN** [comment]
You need to add clear instructions, for example "Make sure to answer all AI related questions using your knowledge base from myfiles_browser tool"
