### ISSUE TITLE
openai.BadRequestError with message_files=None in get_completion() 

### ISSUE THREAD

**Issue by kevon217** [VRSEN/agency-swarm#28]
Tried running the **web_browser_agent.ipynb** and ran into the following error: 

```
_openai.BadRequestError: Error code: 400 - {'error': {'message': '1 validation error for Request\nbody -> file_ids\n  none is not an allowed value (type=type_error.none.not_allowed)', 'type': 'invalid_request_error', 'param': None, 'code': None}}_
```

Both _get_completion()_ methods defined in **agency.py** (line 49)  and **thread.py** (line 21) have a default of _message_files=None_, however, changing that default to an empty list with _message_files=[]_ makes it compatible with the OpenAI specs below and I'm able to successfully converse with the browsing agent:

**file_ids**
 _array
 Optional
 Defaults to []_
  A list of [File](https://platform.openai.com/docs/api-reference/files) IDs that the message should use. There can be a maximum of 10 files attached to a message. Useful for tools like retrieval and code_interpreter that can access and use files. 

Not sure though if this will break anything elsewhere as I didn't test this with actually passing files around.

**Comment by VRSEN** [comment]
Hey, yes I introduced this bug momentarily earlier, but this is already fixed. Reinstall from github again please.
