### ISSUE TITLE
Feature Request: Add attachments to user message

### ISSUE THREAD

**Issue by pythiantech** [VRSEN/agency-swarm#30]
There could be cases where the user may have to give additional files to the assistant apart from the ones that the assistant already has for its functioning. In such scenarios, it would be great if pdf, docx, xlsx etc. could be attached to the user message

**Comment by VRSEN** [comment]
Yes, this is already supported. I also had this request from my client in production. You can now do this by attaching openai file_ids in `message_files` parameter when using `get_completion` from an agency class.
