### ISSUE TITLE
Error code :500

### ISSUE THREAD

**Issue by mr-robotanist** [VRSEN/agency-swarm#31]
The BrowsingAgent seems to be stuck after loading the initial webpage and i received the following

Here is a screenshot from my openai BrowsingAgent
![Screenshot 2023-12-28 194310](https://github.com/VRSEN/agency-swarm/assets/27242359/2260597b-a57e-4d10-ad56-3ffdbc5a5121)

At first I thought it may have to do with the login process, but then i logged in myself and got the Agent to start at step 2 and it encountered the same error.
![Screenshot 2023-12-28 195026](https://github.com/VRSEN/agency-swarm/assets/27242359/ed9c23a0-bacf-40d2-af4f-dce352909095)

**Comment by nairdaee** [comment]
Also getting the same error 500 on my end:

![kra-attempt-4](https://github.com/VRSEN/agency-swarm/assets/60518690/ab067739-e268-4dc7-8bad-d9655efa3dbd)

**Comment by VRSEN** [comment]
This is an OpenAI error, guys. Make sure your accounts are on paid plans, and you are not using VPNs when running the notebook.

**Comment by mr-robotanist** [comment]
Was running from gradio, only went to openai to get the error. Im have tier 5 openai api account so that isnt the issue.

Any other ideas?

**Comment by VRSEN** [comment]
Possibly, vision model had some downtime. Openai say preview models are not yet suited for production traffic. 
![Screenshot 2023-12-30 at 10 51 10 AM](https://github.com/VRSEN/agency-swarm/assets/71930995/ea4d4f82-6fff-4ebb-8539-2fe030ae6741)

Are you still consistently experiencing this? @mr-robotanist

**Comment by mr-robotanist** [comment]
Ya, im guessing everyone is having this issue now?
![Screenshot 2023-12-30 125510](https://github.com/VRSEN/agency-swarm/assets/27242359/d2600e0f-315c-4f55-adb1-8b6a6c42dad1)
