### ISSUE TITLE
Add Support For Azure Openai

### ISSUE THREAD

**Issue by dholakashyap** [VRSEN/agency-swarm#33]
I need Azure Openai Support because it's faster than official Openai.

**Comment by VRSEN** [comment]
I recently added `set_openai_client` method, so you can now pass client with your own configuration like this:

```python
from openai import AzureOpenAI
from agency_swarm.util.oai import set_openai_client

client = AzureOpenAI(
    # https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#rest-api-versioning
    api_version="2023-07-01-preview",
    # https://learn.microsoft.com/en-us/azure/cognitive-services/openai/how-to/create-resource?pivots=web-portal#create-a-resource
    azure_endpoint="https://example-endpoint.openai.azure.com",
    api_key="YOUR_API_KEY"
)

set_openai_client(client)
```

Keep in mind, however, that the Azure API shape differs from the core API shape which means that the static types for responses / params won't always be correct.

**Comment by VRSEN** [comment]
Docs are now available here: https://vrsen.github.io/agency-swarm/advanced-usage/azure-openai/

**Comment by cjlynch278** [comment]
Hey, I'm receiving a "NotFoundError: Resource not found", I'm thinking because Azure OpenAI doesn't support the /assistants endpoint, which agency_swarm depends on.

I've followed the steps outlined in the azure.ipynb file, but still hit the error. When calling using the Azure Open AI chat completion, I get a successful response:  
```
import os
from openai import AzureOpenAI
from agency_swarm import set_openai_client
from agency_swarm import Agent, Agency, set_openai_key

api_base = os.getenv("AZURE_API_BASE")
gpt_deployment = "NBCU-D2C-Peacock-ODR-GPT4"    
api_key = os.getenv("AZURE_GPT_KEY")
api_base = "https://nbcu-d2c-peacock-odr-aai5.openai.azure.com/"
gpt_deployment = "NBCU-D2C-Peacock-ODR-GPT4"

client= AzureOpenAI(
    api_version=api_version,
    azure_endpoint=api_base,
    api_key=AZURE_GPT_KEY
)


response = client.chat.completions.create(
        model = gpt_deployment,
        messages = [
            {"role": "system", "content": 'test'},
            {"role": "user", "content": 'test'}
        ],
        temperature= 1,
        top_p= 1,
        max_tokens= 2000
        
    )
print(response)
```

Then using that same client for the Agency Swarm library, I hit an error: 
```
set_openai_client(client)
agent1 = Agent(name="agent1", description="I am a simple agent", model=gpt_deployment)
ceo = Agent(name="ceo", description="I am the CEO", model=gpt_deployment)
agency = Agency([ceo, [ceo, agent1]])
```

I see that trying to access and '/assistants' endpoint, yet that doesn't exist in azure, unlike open AI. Error stack trace: 

> NotFoundError                             Traceback (most recent call last)
> Cell In[16], line 5
>       1 agent1 = Agent(name="agent1", description="I am a simple agent", model=gpt_deployment)
>       3 ceo = Agent(name="ceo", description="I am the CEO", model=gpt_deployment)
> ----> 5 agency = Agency([ceo, [ceo, agent1]])
> 
> File [~/dev_env/lib/python3.11/site-packages/agency_swarm/agency/agency.py:125](http://localhost:8888/lab/workspaces/auto-4/tree/Projects/ai-enabled-bi-experiments/notebooks/Untitled%20Folder/agency_swarm_tutorial/~/dev_env/lib/python3.11/site-packages/agency_swarm/agency/agency.py#line=124), in Agency.__init__(self, agency_chart, shared_instructions, shared_files, async_mode, settings_path, settings_callbacks, threads_callbacks, temperature, top_p, max_prompt_tokens, max_completion_tokens, truncation_strategy)
>     123 self._parse_agency_chart(agency_chart)
>     124 self._create_special_tools()
> --> 125 self._init_agents()
>     126 self._init_threads()
> 
> File [~/dev_env/lib/python3.11/site-packages/agency_swarm/agency/agency.py:839](http://localhost:8888/lab/workspaces/auto-4/tree/Projects/ai-enabled-bi-experiments/notebooks/Untitled%20Folder/agency_swarm_tutorial/~/dev_env/lib/python3.11/site-packages/agency_swarm/agency/agency.py#line=838), in Agency._init_agents(self)
>     836     if not agent.shared_state:
>     837         agent.shared_state = self.shared_state
> --> 839     agent.init_oai()
>     841 if self.settings_callbacks:
>     842     with open(self.agents[0].get_settings_path(), 'r') as f:
> 
> File [~/dev_env/lib/python3.11/site-packages/agency_swarm/agents/agent.py:245](http://localhost:8888/lab/workspaces/auto-4/tree/Projects/ai-enabled-bi-experiments/notebooks/Untitled%20Folder/agency_swarm_tutorial/~/dev_env/lib/python3.11/site-packages/agency_swarm/agents/agent.py#line=244), in Agent.init_oai(self)
>     242                     continue
>     244 # create assistant if settings.json does not exist or assistant with the same name does not exist
> --> 245 self.assistant = self.client.beta.assistants.create(
>     246     model=self.model,
>     247     name=self.name,
>     248     description=self.description,
>     249     instructions=self.instructions,
>     250     tools=self.get_oai_tools(),
>     251     tool_resources=self.tool_resources,
>     252     metadata=self.metadata,
>     253     temperature=self.temperature,
>     254     top_p=self.top_p,
>     255     response_format=self.response_format,
>     256 )
>     258 if self.assistant.tool_resources:
>     259     self.tool_resources = self.assistant.tool_resources.model_dump()
> 
> File [~/dev_env/lib/python3.11/site-packages/openai/resources/beta/assistants.py:135](http://localhost:8888/lab/workspaces/auto-4/tree/Projects/ai-enabled-bi-experiments/notebooks/Untitled%20Folder/agency_swarm_tutorial/~/dev_env/lib/python3.11/site-packages/openai/resources/beta/assistants.py#line=134), in Assistants.create(self, model, description, instructions, metadata, name, response_format, temperature, tool_resources, tools, top_p, extra_headers, extra_query, extra_body, timeout)
>      64 """
>      65 Create an assistant with a model and instructions.
>      66 
>    (...)
>     132   timeout: Override the client-level default timeout for this request, in seconds
>     133 """
>     134 extra_headers = {"OpenAI-Beta": "assistants=v2", **(extra_headers or {})}
> --> 135 return self._post(
>     136     "[/assistants](http://localhost:8888/assistants)",
>     137     body=maybe_transform(
>     138         {
>     139             "model": model,
>     140             "description": description,
>     141             "instructions": instructions,
>     142             "metadata": metadata,
>     143             "name": name,
>     144             "response_format": response_format,
>     145             "temperature": temperature,
>     146             "tool_resources": tool_resources,
>     147             "tools": tools,
>     148             "top_p": top_p,
>     149         },
>     150         assistant_create_params.AssistantCreateParams,
>     151     ),
>     152     options=make_request_options(
>     153         extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
>     154     ),
>     155     cast_to=Assistant,
>     156 )
> 
> File [~/dev_env/lib/python3.11/site-packages/openai/_base_client.py:1260](http://localhost:8888/lab/workspaces/auto-4/tree/Projects/ai-enabled-bi-experiments/notebooks/Untitled%20Folder/agency_swarm_tutorial/~/dev_env/lib/python3.11/site-packages/openai/_base_client.py#line=1259), in SyncAPIClient.post(self, path, cast_to, body, options, files, stream, stream_cls)
>    1246 def post(
>    1247     self,
>    1248     path: str,
>    (...)
>    1255     stream_cls: type[_StreamT] | None = None,
>    1256 ) -> ResponseT | _StreamT:
>    1257     opts = FinalRequestOptions.construct(
>    1258         method="post", url=path, json_data=body, files=to_httpx_files(files), **options
>    1259     )
> -> 1260     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
> 
> File [~/dev_env/lib/python3.11/site-packages/openai/_base_client.py:937](http://localhost:8888/lab/workspaces/auto-4/tree/Projects/ai-enabled-bi-experiments/notebooks/Untitled%20Folder/agency_swarm_tutorial/~/dev_env/lib/python3.11/site-packages/openai/_base_client.py#line=936), in SyncAPIClient.request(self, cast_to, options, remaining_retries, stream, stream_cls)
>     928 def request(
>     929     self,
>     930     cast_to: Type[ResponseT],
>    (...)
>     935     stream_cls: type[_StreamT] | None = None,
>     936 ) -> ResponseT | _StreamT:
> --> 937     return self._request(
>     938         cast_to=cast_to,
>     939         options=options,
>     940         stream=stream,
>     941         stream_cls=stream_cls,
>     942         remaining_retries=remaining_retries,
>     943     )
> 
> File [~/dev_env/lib/python3.11/site-packages/openai/_base_client.py:1041](http://localhost:8888/lab/workspaces/auto-4/tree/Projects/ai-enabled-bi-experiments/notebooks/Untitled%20Folder/agency_swarm_tutorial/~/dev_env/lib/python3.11/site-packages/openai/_base_client.py#line=1040), in SyncAPIClient._request(self, cast_to, options, remaining_retries, stream, stream_cls)
>    1038         err.response.read()
>    1040     log.debug("Re-raising status error")
> -> 1041     raise self._make_status_error_from_response(err.response) from None
>    1043 return self._process_response(
>    1044     cast_to=cast_to,
>    1045     options=options,
>    (...)
>    1049     retries_taken=options.get_max_retries(self.max_retries) - retries,
>    1050 )
> 
> NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

**Comment by DanAIDev** [comment]
@cjlynch278 did you try to update the api version? Azure OpenAi does support Assistants API but not in every version. I had an issue with it too, specifically with tool_resources parameter and the solution was to update the api version as explained here: https://github.com/openai/openai-python/issues/1449
