### ISSUE TITLE
requests are timing out after assistants are initially made

### ISSUE THREAD

**Issue by MrCredible** [VRSEN/agency-swarm#35]
I can see that the assistants have been made in my openai account with the correct names and instructions, but appears there is a timeout while still in the create assistants function of openai's package.

**Comment by VRSEN** [comment]
The timeout is set to 10 minutes by default. Check your connections please, and make sure you are not using VPN. Also, I recently increased `max_retries` on open ai client to 5. Pull from main, reinstall and let me know if this helps.
