### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by schauppi** [VRSEN/agency-swarm#37]
Do you have an discord server for this project?

**Comment by VRSEN** [comment]
Coming up this week🤫

**Comment by yanniedog** [comment]
Looking forward to it :)

**Comment by VRSEN** [comment]
There you go guys! Feel free to join: https://discord.gg/y24DBzCh

**Comment by erissatallan** [comment]
Invite link is now invalid. Please share another.

**Comment by bonk1t** [comment]
https://discord.gg/cw2xBaWfFM
