### ISSUE TITLE
Notebook JSON is invalid: 'execution_count' is a required property

### ISSUE THREAD

**Issue by OrwellianOwl** [VRSEN/agency-swarm#41]
[E 20:56:09.963 NotebookApp] Notebook JSON is invalid: 'execution_count' is a required property
    
    Failed validating 'required' in code_cell:
    
    On instance['cells'][3]:
    {'cell_type': 'code',
     'id': 'b3bb4f042e4b3050',
     'metadata': {'collapsed': False},
     'outputs': ['...0 outputs...'],
     'source': 'from agency_swarm import set_openai_key\n'
               'set_openai_key("YOUR_OPE...'}

Getting this error when I open the notebook for the first time.

**Comment by VRSEN** [comment]
@OrwellianOwl seems like PyCharm is messing with Jupyter. Can you pull and try again? Reopen if the problem persists.
