### ISSUE TITLE
No module named 'agency_swarm'

### ISSUE THREAD

**Issue by ai-made-approachable** [VRSEN/agency-swarm#50]
Whatever I try, I cannot get the notebook running.
![image](https://github.com/VRSEN/agency-swarm/assets/149181237/a7dd6f61-7e13-419e-acc5-1f4e7cd81b41)

- I did ```pip install -r requirements.txt``` in the agency_swarm directory. 
- I can also see that '../agency_swarm' was added properly to the sys.path
- My agency_swarm folder contains the local agency_swarm module
![image](https://github.com/VRSEN/agency-swarm/assets/149181237/79d362fd-7695-4239-bf8c-5fe545e1bb22)

Any ideas? I also tried changing the sys.path, but to no avail.

**Comment by ai-made-approachable** [comment]
Anything wrong about my installation routine? Btw if you are interested I can create a pull request for them.

# How to install agency-swarm
## Install software
- Install Git: https://docs.github.com/en/desktop/installing-and-authenticating-to-github-desktop/installing-github-desktop
- Install miniconda: https://docs.conda.io/projects/miniconda/en/latest/miniconda-install.html

## Install Project (Only Once):
-   Open terminal.
-   Clone the project: ```git clone https://github.com/VRSEN/agency-swarm.git```.
-   Navigate into the folder: ```cd agency-swarm```.
-   Create the conda environment: ```conda create --name venv```
-   Activate the conda environment: ```conda activate venv```.
-   Install the requirements: ```pip install -r requirements.txt```.
-   Install Jupyter Notebook: ```pip install jupyter```.

## Run Project:
-   Open terminal.
-   Navigate to the project folder if not already there: ```cd agency-swarm```
-   Activate the conda environment: ```conda activate venv```.
-   Start Jupyter Notebook: ```jupyter notebook```.
- Navigate to /agency-swarm/notebooks/ folder
- Select file "genesis_agency.ipynb" and press "Open"-Button
- If your browser is blocking the popup enable it OR open this URL instead to directly go to the file: http://localhost:8888/notebooks/genesis_agency.ipynb
- Replace the Open AI API Key in the 3rd cell with your API Key
- Now one by one run each cell: Select a cell and then either press the run-icon or press Shift + Enter

**Comment by wealthypotato** [comment]
Have you had the chance to find a solution?

**Comment by ai-made-approachable** [comment]
No. I was hoping VRSEN would take a look. Really excited about this project.

**Comment by fylingpete** [comment]
Try the following:

pip uninstall agency_swarm

and then install the new library with

pip install agency-swarm

**Comment by ai-made-approachable** [comment]
Yeah that solves it! Thank you very much :)
