### ISSUE TITLE
Agency creation failing with hallucination

### ISSUE THREAD

**Issue by OscarsOrbit** [VRSEN/agency-swarm#52]
Hello

I have ran several tests for this and I am unable to get a simple agency created. Not sure if it's due to the folder structure not being picked up properly, but today as I tried again, I noticed something:

When I looked inside my OpenAI assistants page, I saw the created assistants don't have proper instructions sent. I am not sure if it's supposed to look like this? I'm guessing this should have the actual instructions and not just a reference to the file path:

![image](https://github.com/VRSEN/agency-swarm/assets/150558376/dbcb16c0-d2f1-47a4-b3ec-514e79f14ece)

This is after running a clean install of agency swarm.

I asked for a relatively small task just to test it, like so:

![image](https://github.com/VRSEN/agency-swarm/assets/150558376/37ab7f27-ddf9-43fe-bc57-921d875aa59e)

I'm not sure this is the correct flow, because only the "GenesisCEO" agent is acting here. Is this the intended behavior? It looked different in your video demo @VRSEN 

Also, check out where the agency has been added:

![image](https://github.com/VRSEN/agency-swarm/assets/150558376/efa14a1b-55b1-47dc-8d67-814516b41bfe)

It's been added in the path  **/agency-swarm/notebooks/(agencyname)/(agencyname)/**

Is this the intended behavior? - my guess would have been that the agency would be added to the /agency-swarm/agency/(agencyname) path and the agents (which, none were created) would be added to the /agency-swarm/agency/(agentname) path.

Am I missing something here?

_The CEO agent seems to think the agency was successfully created_, but it doesn't give me instructions to run the agency.py file even like it's supposed to at the end when the task has been completed.

Any help to get this working correctly is highly appreciated.

**Comment by TylerAlmeida** [comment]
I encountered the same issue with the genesis agency (hallucination, adding nested agents to notebooks path) and think I'm going to end up just custom creating the agency I need. Definitely following here to see if this is intended or a known issue

**Comment by VRSEN** [comment]
Seems like this issue is only happening on windows @OscarsOrbit. Can you please try to modify this method in agent.py https://github.com/VRSEN/agency-swarm/blob/6bbd3c75bcf2dc932b41763cc0b18bbfee3bd33d/agency_swarm/agents/agent.py#L461 and let me know if you manage to fix this? The path is incorrect for some reason

**Comment by Satal** [comment]
@VRSEN, just to let you know I've pulled the latest code on my WSL machine, and I'm getting the same error.

Let me know if there's a particular way you want the `get_class_folder_path` to be adjusted, and I'll try running that on my way home from work 😊

**Comment by OscarsOrbit** [comment]
@Satal thanks to @VRSEN for showing where to make changes, I have done the following and it worked for me:

1- Use pathlib to handle the path/directory by adding the following line to the top of the **agent.py** file:

`from pathlib import Path`

2- Find the following lines in your agent.py file:

`def get_class_folder_path(self):
    return os.path.abspath(os.path.dirname(inspect.getfile(self.__class__)))
`
3- Replace them with our newly added pathlib method:

`def get_class_folder_path(self):
    return str(Path(__file__).parent.resolve())`
    
 4- Run the Genesis Agency Creator (I ran it in the gradio window) and now the agents are being properly created with their manifestos, files, etc. as seen in VRSEN's video demo.
 
 I am not sure if this is the best way to go about it, but it worked for me. Please check on your end @Satal and confirm if you are also having some success with this.
 
 I will do some more testing of the framework myself. The path issue seems to be resolved for me though with those changes. Cheers!

**Comment by VRSEN** [comment]
@Satal @vlada-kopric @OscarsOrbit can you guys please reinstall from main and let me know if the problem persists? Thanks!

**Comment by Satal** [comment]
Unfortunately, the same issue. `rm -rf`'d the previous agency swarm directory, git cloned main, created new conda environment, `pip install -r requirements.txt`, started jupyter notebook from the notebooks directory, opened `genesis_agency.ipynb`, updated the openai key and ran all.

The following is the totality of the chat
<img width="923" alt="image" src="https://github.com/VRSEN/agency-swarm/assets/3852030/7e380328-6cbb-4587-86db-6ae4f4a3d605">

And here is the directory
<img width="192" alt="image" src="https://github.com/VRSEN/agency-swarm/assets/3852030/1471c31d-aa41-4b95-87e4-65c60e22859f">

And just because I had that bit of the code open, here's the code that I have for `get_class_folder_path`
<img width="481" alt="image" src="https://github.com/VRSEN/agency-swarm/assets/3852030/05cf27bb-9942-4017-b630-a69cb810438d">

Thank you for the creation of this and your continued help on this.

**Comment by Satal** [comment]
Unfortunately, I'm still not seeing any agents created :-(

The following was all done on a Windows 11 laptop, using WSL2 (Ubuntu), Google Chrome (on laptop) for the browser) and Python 3.11.7.
`rm -rf`'d the old agency swarm dir
git cloned main
created/activated a new conda env
`pip install -r requirements.txt`
Opened notebooks dir
Ran `jupyter notebook`
Opened `genesis_agency.ipynb`
Changed the openai key ran all steps
Opened gradio using link
Sent " I need an agency to create multi-user laravel applications. For the front-end it should use Tailwind CSS and alpineJS" 

I am seeing the following error at the beginning
<img width="912" alt="image" src="https://github.com/VRSEN/agency-swarm/assets/3852030/bc7729e9-5833-4278-84b3-0400b8ffe296">

Also is the contents of `agency_manifesto.md` supposed to look like this?
<img width="241" alt="image" src="https://github.com/VRSEN/agency-swarm/assets/3852030/b6b8606a-b5bb-42b3-9330-a02d9684f076">

There is no `manifesto.md`

<img width="184" alt="image" src="https://github.com/VRSEN/agency-swarm/assets/3852030/993fae29-8435-4de5-9c21-4f2e1b76d4e0">

**Comment by VRSEN** [comment]
Hey @Satal, if you ran the first cell in the notebook, you probably installed it from pip again, which has an old version. Try uninstalling it again and running `pip install .`, instead from the root directory.

**Comment by Satal** [comment]
Thanks @VRSEN, sorry about that. I've done it again but not running the pip install.

I'm now getting 
<img width="186" alt="image" src="https://github.com/VRSEN/agency-swarm/assets/3852030/c0eb67ca-4a94-472e-a71c-487812e352c3">
It appears that one thing is going inside another.

Also when you go into agency.py this is the code I have
<img width="316" alt="image" src="https://github.com/VRSEN/agency-swarm/assets/3852030/15d6ddfa-fab4-4c1b-8990-76e01d1eabfe">

**Comment by VRSEN** [comment]
@Satal did you check the instructions of the genesis agency? Do they still show 'manifesto.md' or are they correct?
