### ISSUE TITLE
No module named 'agency_swarm.agency.genesis'

### ISSUE THREAD

**Issue by wealthypotato** [VRSEN/agency-swarm#54]
![image](https://github.com/VRSEN/agency-swarm/assets/130777383/942a1203-3d13-4d5c-980f-78c631131132)

i followed the tutorial provided by the guru, i even edited the path folders and ran miniconda in order to create the virtual env but no luck, i was hoping anyone else who has ran into this issue has found a way around it

**Comment by Leonai-do** [comment]
Same error

**Comment by fylingpete** [comment]
just run the following commands in your conda env. 

pip uninstall agency_swarm

and then install the new library with 

pip install agency-swarm

**Comment by Leonai-do** [comment]
> just run the following commands in your conda env.
> 
> pip uninstall agency_swarm
> 
> and then install the new library with
> 
> pip install agency-swarm

It worked, thanks, I recommend to pip install gradio and selenium to avoid error before running the cells on jupyter.
