### ISSUE TITLE
Issues for Europeans with google search

### ISSUE THREAD

**Issue by ai-made-approachable** [VRSEN/agency-swarm#55]
At the moment agency-swarm fails when it tries to use google search. The way it uses the function is correct thought + also the generated URL.

E.g.
[https://google.com/search?q=prompt+optimization+API+for+natural+language+processing"}](https://google.com/search?q=prompt+optimization+API+for+natural+language+processing%22%7D)', name='ReadURL')

This is most likely because of GDPR. If you open google in a private browser tab from Europe you will see this:
![image](https://github.com/VRSEN/agency-swarm/assets/149181237/4190aebe-57e2-4e02-91b0-f96ba02c8322)

To make this work it would need to accept the terms.

**Comment by VRSEN** [comment]
Interesting. Can you please modify the ReadURL tool to include a check if this modal is present, and close it accordingly with selenium? @ai-made-approachable
