### ISSUE TITLE
Read URL Tool unknown error

### ISSUE THREAD

**Issue by jonwash** [VRSEN/agency-swarm#56]
Getting an unknown error with the read URL tool

![Screenshot 2024-01-19 155239](https://github.com/VRSEN/agency-swarm/assets/12816809/c4c6d6d6-79ae-44da-b9f7-23826c63f65d)

**Comment by sigmaeni** [comment]
Check the output of your jupyter notebook. In my case it was suggesting that I was missing `webdriver-manager` and `selenium-stealth`. A quick pip install of those sorted it out for me.

**Comment by jonwash** [comment]
fixed
