### ISSUE TITLE
name 'GenesisAgency' is not define

### ISSUE THREAD

**Issue by newjxmaster** [VRSEN/agency-swarm#60]
i get the following
--------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 test_agency = GenesisAgency()

NameError: name 'GenesisAgency' is not define

<img width="900" alt="Screenshot 2024-01-24 at 07 08 45" src="https://github.com/VRSEN/agency-swarm/assets/35283865/fbb922e4-d4d7-4e53-9e36-05fb2d8c2072">

**Comment by VRSEN** [comment]
Uninstall and reinstall from pip please before running this notebook with `pip install agency-swarm`
