### ISSUE TITLE
Unable to get to internet

### ISSUE THREAD

**Issue by vlada-kopric** [VRSEN/agency-swarm#64]
I've tried to run it several time and keep getting this error.
🐦 BrowsingAgent 🛠️ Executing Function
Function(arguments='{"url":"[https://google.com/search?q=social+media+post+creation+and+analytics+API+for+Twitter+and+LinkedIn"}](https://google.com/search?q=social+media+post+creation+and+analytics+API+for+Twitter+and+LinkedIn%22%7D)', name='ReadURL')

🐦 ReadURL ⚙️Function Output
Error: Message: Service /Users/vlada/.wdm/drivers/chromedriver/mac64/120.0.6099.109/chromedriver-mac-arm64/chromedriver unexpectedly exited. Status code was: -9

**Comment by VRSEN** [comment]
Try quitting chrome before using the browsing agent. Let me know if this helps. @vlada-kopric

**Comment by vlada-kopric** [comment]
yes, it did help.
