### ISSUE TITLE
Feedback: Using Zapier in the introductory tutorial notebook is a bad UX

### ISSUE THREAD

**Issue by afewell** [VRSEN/agency-swarm#66]
I am really excited to use this project, I love the design decisions and if all goes well I would like to be a regular user and contributor. 

I know in the tutorial notebook it says zapier is optional, but I would really like to learn as much as I can so I thought I would try, and I have never had such a frustrating experience trying to get an API key. I think they have changed their UI as all the bots are wrong, perplexity is wrong, your chatbot is wrong, all the instructions I can find are wrong. There is no option to create an app, their is a section that says apps, but when you create new you can create several things, none of which is an app. And yes I am using the developer platform. The default option to create a zap from the developer platform is an AI workflow that tries to use AI to build your zap, so using a value like "Agency Swarm Integration" as suggested by the Swarm Agent Chatbot doesnt work. There is an option to switch to manually create Zap, but its not even save-able until I configure at least one trigger and 1 action. The NLA Instructions say to connect your account to a custom action, but it is not usable until you select an available existing action from their list, I cannot find any way around it. 

I have used a LOT of API's from a lot of sites, gotten a lot of api keys, never had much trouble until zapier, and I know it says the option can be skipped but I think putting something like this which can easily lead to frustration in the introductory tutorial which has a high risk of making people frustrated before they can even try agency swarm, and the problem has nothing to do with agency swarm. 

I am not trying to insist that something be changed for my benefit, just offering a suggestion as I think not using the zapier integration in the introductory tutorial and maybe making it a separate example would be a better user experience and create a better assurance that new users have a good experience when first trying out agency swarm. 

Thank you!

**Comment by afewell** [comment]
For clarity the link to the introductory tutorial notebook I am using is from the video, not on this repo. The link provided is https://colab.research.google.com/drive/1qGVyK-vIoxZD0dMrMVqCxCsgL1euMLKj#scrollTo=sY8FY_UwLKy_&uniqifier=2

Thanks!

**Comment by VRSEN** [comment]
Thanks for feedback @afewell. I totally agree with you. This notebook was created a long time ago, and needs an update. Do you have any suggestions for which tools to replace them with?

**Comment by arnavsaxena17** [comment]
Get zapier key here : https://nla.zapier.com/credentials/

**Comment by afewell** [comment]
Wow Thanks for such a quick response ... honestly I wasnt expecting such a rapid response and I'd hoped to already have some updates to commit. I am still finding my way around but I will plan to make a PR with some revised suggestions for the notebook soon. If you would prefer to close this please feel free or if you want to leave it open I will reference it in my PR when I am able to propose an update. 

Seeing such a supportive community here is extremely encouraging! Thanks again so much!

**Comment by afewell** [comment]
Im going to go ahead and close this as the feedback has been received, additional guidance for finding the zapier key was provided (thanks [arnavsaxena17](https://github.com/arnavsaxena17)), although even with the API key it did not work for me, it seems like additional setup of zapier may be required. In any case I know Arsenii mentioned he has hired someone for documentation, I also created a introductory notebook and tutorial, so I think its fine to close this issue. Thanks!
