### ISSUE TITLE
Enhance Agency class to support optional public sharing in Gradio demos

### ISSUE THREAD

**Issue by afewell** [VRSEN/agency-swarm#68]
I am working on adding the tutorial notebook and ran into an issue. When running the notebook in colab, you can see when you launch gradio it gives an error that the value for share must equal True to launch a public interface, but, colab has some underlying settings that override this and launch the public url anyway. 

But, if you try running the notebook with jupyter it doesnt launch the public url. And if you are running the notebook from within a container, it will only launch on 127.0.0.1 from within container which is not accessible. You could enable passing through the ability to set the ip address and launch it to 0.0.0.0, but for my use case it would suffice to simply enable passing through the sharing setting. 

I think I will also need this when I get past the notebooks and am running it as a python project as my typical dev environment is a container running on a remote k8s cluster so if I use gradio it will be nice to have this option. 

I have already modified and tested updating the demo_gradio function to leave the default value of share=False but allow the share=True option to be passed in when calling `agency.demo_gradio(height=900, share=True)`. 
![Screenshot 2024-01-31 at 11 53 55 PM](https://github.com/VRSEN/agency-swarm/assets/17549071/83e5fe8a-d03f-40cd-a8f0-38a09a0ba2cf)

I will submit a PR to resolve this issue shortly, I am not sure if you normally allow PR's without an associated issue ticket but in case I wanted to submit this ticket in advance of the PR to provide a clear explanation. 

I'm sure you will see the diff in the PR I submit, but if you want to see the reference from my fork its here: https://github.com/afewell/agency-swarm/commit/588d671093a2148461a005220746b64465ea0446

Thanks!

**Comment by VRSEN** [comment]
Thank you, I will merge soon.
