### ISSUE TITLE
Add options for other open-ai models

### ISSUE THREAD

**Issue by okoliechykwuka** [VRSEN/agency-swarm#7]
I tried testing out agency-swarm via the collab notebook but I ran into an error. This might be as a result of not having access to `gpt-4-1106-preview` models

---------------------------------------------------------------------------
BadRequestError                           Traceback (most recent call last)
[<ipython-input-27-8b35373cda7a>](https://localhost:8080/#) in <cell line: 3>()
      1 from agency_swarm import Agency
      2 
----> 3 agency = Agency([
      4     ceo,
      5     [ceo, dev],

6 frames
[/usr/local/lib/python3.10/dist-packages/openai/_base_client.py](https://localhost:8080/#) in _request(self, cast_to, options, remaining_retries, stream, stream_cls)
    875             # to completion before attempting to access the response text.
    876             err.response.read()
--> 877             raise self._make_status_error_from_response(err.response) from None
    878         except httpx.TimeoutException as err:
    879             if retries > 0:

BadRequestError: Error code: 400 - {'error': {'message': "The requested model 'gpt-4-1106-preview' does not exist.", 'type': 'invalid_request_error', 'param': 'model', 'code': 'model_not_found'}}

**Comment by cemkod** [comment]
I checked the code. It is possible to pass the model to the agent constructor like this:

ceo = Agent(name="CEO",
            description="Responsible for client communication, task planning and management.",
            instructions=ceo_instructions, # can be a file like ./instructions.md
            files_folder=None,
            model="gpt-3.5-turbo-1106",
            tools=[])

**Comment by VRSEN** [comment]
Yes, you can pass a model in the model parameter, if it is supported by assistants api. I will add docstrings soon
