### ISSUE TITLE
Calls to OpenAI Assistants API seem to be timing out

### ISSUE THREAD

**Issue by mtessar** [VRSEN/agency-swarm#71]
Hello,

I am experiencing the following error in both my production environment and my dev environment:

openai.BadRequestError: Error code: 400 - {'error': {'message': 'Runs in status "expired" do not accept tool outputs.', 'type': 'invalid_request_error', 'param': None, 'code': None}}

Here are the relevant entries from higher up on the stack trace.  

File "/home/webapp/nice_chat/backend/chatenv/lib/python3.10/site-packages/agency_swarm/threads/thread.py", line 90, in get_completion

    self.run = self.client.beta.threads.runs.submit_tool_outputs(

  File "/home/webapp/nice_chat/backend/chatenv/lib/python3.10/site-packages/openai/resources/beta/threads/runs/runs.py", line 349, in submit_tool_outputs

    return self._post(

This is happening fairly regularly but not always.  Please let me know if you need additional information or have any suggestions.

**Comment by mtessar** [comment]
This seems to happen with both versions 0.1.0 and 0.1.1 as well

**Comment by VRSEN** [comment]
Hey @mtessar, how long does it take to execute your tool? Also is this happening on SendMessage tools or custom ones?

**Comment by mtessar** [comment]
It was on SendMessage/calls to the OpenAI assistants API. I think it's possible it was an OpenAI issue as mid day today it cleared up and reliability returned. 

If I wanted to set a timeout on OpenAI calls, is that a parameter I can set through Agency Swarm, or should I set that on the global OpenAI client object?

**Comment by VRSEN** [comment]
I successfully replicated the issue you described. It arises with large swarms, where the top-level agents experience prolonged waits for responses. This delay causes the run on OpenAI to expire. I plan to address this problem in the forthcoming release.

To configure the timeout for the OpenAI client, you can employ the following code snippet:

```python
from agency_swarm.util.oai import set_openai_client

client = OpenAI(
    # Set timeout to 20 seconds (default is 10 minutes)
    timeout=20.0,
)

set_openai_client(client)
```

Please note, however, that this timeout setting is distinct from the run timeouts on OpenAI. As such, increasing this timeout value will not fix the error you referenced above.

**Comment by mtessar** [comment]
Thanks @VRSEN - in my case the root cause does seem to be a timeout in one of the called agents. This would cause the same issue you identified which would be a long running CEO that is expired by the time the called agent responds.  Please let me know if there is anything I can do to help test your fix.

**Comment by VRSEN** [comment]
Show be fixed in latest
