### ISSUE TITLE
Unable to create multiple threads/ conversations for a single agent/ assistant

### ISSUE THREAD

**Issue by arnavsaxena17** [VRSEN/agency-swarm#72]
I saw the module on threads, is there an example/ function that allows an Agent to converse with multiple participants across multiple threads - this is available in assistants api with creating a new thread_id. 

How can we extend this to the Agent object?

**Comment by VRSEN** [comment]
Hey, if you define communication flows like below, it means that CEO can chat with both dev or va in separate threads.

```
agency = Agency([
    ceo,
    [ceo, dev],  
    [ceo, va],  
])
```

**Comment by arnavsaxena17** [comment]
Since each node is an assistant; the assistant should be able to spawn multiple threads. Eg. one assistant should be able to converse with multiple customers to create proposals and the dev should be able to converse with other users regarding their work. The CEO should not be the only entry point for all external interactions IMHO.

**Comment by VRSEN** [comment]
In the upcoming release you will be able to select multiple agents as the entry point for communication, similar to chatgpt mentions feature. I will probably post it tomorrow
