### ISSUE TITLE
model abstraction layer

### ISSUE THREAD

**Issue by afewell** [VRSEN/agency-swarm#78]
Its not ideal that specific model names are being hardcoded into tools. Even if model abstraction is not the first feature on the roadmap, not abstracting the models is a blocker for a number of different potential features, even if only using openai I may want to try a different model for a function, maybe for cost savings, maybe for performance improvement etc... I may want to use Azure which uses deployment rather than model names, and of course I may want to introduce support for other private or oss model providers at some point. Step 1 for any of these would be providing a model abstraction.

**Comment by afewell** [comment]
for example currently to use azure I will try to make it work by naming model deployments to the same string you have hardcoded as the model in the function, I think that should work, but it still wont work without source code change because you use "gpt-3.5-turbo" as a model name and the dot isnt an allowed character in azure deployment names

**Comment by VRSEN** [comment]
Hey @afewell, what do you mean the model is hardcoded into tools? You can set any model or deployment name when initializing your agent. Here is code snippet on how to use azure:

```python
from openai import AzureOpenAI
from agency_swarm import Agent, Agency, set_openai_client

client = AzureOpenAI(
    api_key=os.getenv("AZURE_OPENAI_KEY"),
    # https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#rest-api-versioning
    api_version="2024-02-15-preview",
    # https://learn.microsoft.com/en-us/azure/cognitive-services/openai/how-to/create-resource?pivots=web-portal#create-a-resource
    azure_endpoint=os.getenv("AZURE_ENDPOINT"),
    timeout=5,
    max_retries=5,
)

set_openai_client(client)

agent1 = Agent(name="agent1", description="I am a simple agent", model='your-azure-deployment-name')

ceo = Agent(name="ceo", description="I am the CEO", model='your-azure-deployment-name')

agency = Agency([ceo, 
                 [ceo, agent1]])
```

Simply replace model with your deployment name on Azure.

Keep in mind, however, that certain capabilities like uploading files are still not available via Azure.

**Comment by afewell** [comment]
Sorry for my mistake and thanks for the clarification!
