### ISSUE TITLE
Feature Request - Containerized version

### ISSUE THREAD

**Issue by Satal** [VRSEN/agency-swarm#81]
I've seen quite a few people (including myself) struggling to get the code working despite following what you're doing on a video or the guides. This could be due to any number of environmental factors.

Implementation of this in a container should remove this issue.

**Comment by Satal** [comment]
So I thought I'd start by making one myself as I wasn't able to get agency-swarm working on my machine.
I've made it available at https://github.com/Satal/agency-swarm-docker, though more than happy if @VRSEN wishes to do the same thing in the core repository.

**Comment by VRSEN** [comment]
Thanks @Satal, can you please create a pull with this docker file in this repo instead? https://github.com/VRSEN/agency-swarm-lab

**Comment by VRSEN** [comment]
Created and merged docker files in agency-swarm-lab
