### ISSUE TITLE
some minor issues

### ISSUE THREAD

**Issue by obaidmuneer** [VRSEN/agency-swarm#85]
![image](https://github.com/VRSEN/agency-swarm/assets/96944978/8d3af307-48dc-4760-b1b7-f9fedf933dcd)
![image](https://github.com/VRSEN/agency-swarm/assets/96944978/39f38065-cf2e-44d9-a4b5-90f7d1ecf5a8)

First there are some time timeout issue idk why 
2nd as yellow labels are hiding my input labels which some time I think my agent is being confused to enter data in same input field again without adding the data in 2nd field and moving forward.

**Comment by VRSEN** [comment]
Some websites might have weird html structure which can cause these issues. Anyway, upgrade to the latest release and reimport new browsing agent please
