### ISSUE TITLE
Third-Party LLM Support

### ISSUE THREAD

**Issue by slavakurilyak** [VRSEN/agency-swarm#92]
I'm seeing solid performance of Claude 3 Opus over GPT-4 Turbo

Have you considered adding third-party LLM providers to further improve the performance of `agency-swarm`?

It would be great to see [anthropic](https://pypi.org/project/anthropic/)  Python library support for `agency-swarm` since it provides 200K token length (vs 128K for OpenAI)

With the [API release of Gemini 1.5 Pro](https://twitter.com/JeffDean/status/1770653917543870571), I anticipate that `agency-swam` will also benefit from the 1M input token length of this model

I recognize that Claude 3 struggles with JSON mode (reported [here](https://x.com/DeepAIWriter/status/1771109500860215501))

I am wondering how well Claude 3 (or Gemini 1.5 Pro) performs with `instructor` by [@jxnl](https://github.com/jxnl)

**UPDATE: 2024-04-27**

Seeing remarkable results with using Llama 3 models hosted on Groq!

Also, compliant-heavy industries (ex healthcare, government, fintech) would benefit from using this framework as they need to select model providers and database/CMS providers to stay compliant

**Comment by jmdevall** [comment]
Let me inform, I am not expert in the api of openai, but recently "NousResearch" released a tuned version of 7B mistral that I think operates with tools as chatgpt do... it seems that it was trained with prompt format with function calling and json, although I don't know the real differences (apart of the inference power due it is only a 7B model)  https://huggingface.co/NousResearch/Hermes-2-Pro-Mistral-7B

**Comment by VRSEN** [comment]
I plan to test this next week: https://github.com/datastax/astra-assistants-api I'll let you know the results. Any contributions are welcome!

**Comment by StL-Jim** [comment]
> I plan to test this next week: https://github.com/datastax/astra-assistants-api I'll let you know the results. Any contributions are welcome!

What about going the [ollama](https://github.com/ollama/ollama) or [litellm](https://github.com/BerriAI/litellm)?

**Comment by VRSEN** [comment]
Done. We will keep track of all supported backend assistants api implementations in docs: https://vrsen.github.io/agency-swarm/advanced-usage/open-source-models/

**Comment by phact** [comment]
I was testing further and noticed this issue https://github.com/datastax/astra-assistants-api/issues/40. Right now agency-swarm seems to work great without file-search. Switching to prefixed IDs should fix retrieval.
