### ISSUE TITLE
fix (Readme Banner Image): Please replace the banner with a simpler one without the VRSEN (no offend)

### ISSUE THREAD

**Issue by cutmasta-kun** [VRSEN/agency-swarm#94]
Yeah, pretty much the title. Please replace the banner image with a more streamlined one. Maybe one-color and the icon? 
No offense to VRSEN, but I would like to recommend this framework more, but if this framework wants to survive on it's own, then this should be considered.

Much love

**Comment by VRSEN** [comment]
Yeah, I understand. I have ordered a proper logo and everything. Thanks for feedback!

**Comment by VRSEN** [comment]
This is done now, sorry for a delay
