### ISSUE TITLE
Can not process data in Custom Tools

### ISSUE THREAD

**Issue by thanhmcisai** [VRSEN/agency-swarm#96]
Hi all, 
I faced a problem that I can not receive or find any upload images or upload files in the custom tool. My purpose is that create a tool can process a specific job like detect object or OCR image and then return the result as a output of agent. What must I do for this task. Beside that, what about the custom tool can return another data types like image and return this image for user response.

**Comment by VRSEN** [comment]
Hey, I suggest using a file system for this purpose. Your agents can exchange file paths, or you can store the file in the shared_state within one tool and access it from another. For more tips, visit https://vrsen.github.io/agency-swarm/advanced-usage/tools/#pro-tips
